gmscompat: add workaround for a rare startForeground() crash
Sometimes, startForeground() throws
java.lang.SecurityException: Starting FGS with type $type requires $permissions and the app must be
in the eligible state/exemptions to access the foreground only permission

despite the app both having the required permissions and being in a foreground state.

This issue is hard to reproduce. It's not clear whether it's a GmsCompat bug or an upstream bug in
handling of while-in-use permissions.

Signed-off-by: Dmitrii <bankersenator@gmail.com>